### ISSUE TITLE
Can't import

### ISSUE THREAD

**Issue by alekseyp** [mvonthron/munin-influxdb#2]
Hi there,

I can't figure out why import fails.
It doesn't show an error itself, maybe you can help to find the problem.
Here is my log:

```
# ./muninflux import
Munin to InfluxDB migration tool
--------------------
Exploring Munin structure
  ✗ Could not process datafile (/var/lib/munin/datafile), will read www and RRD cache instead
Reading Munin www cache: (/var/cache/munin/www)
/usr/local/lib/python2.7/dist-packages/bs4/__init__.py:166: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("html5lib"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

To get rid of this warning, change this:

 BeautifulSoup([your markup])

to this:

 BeautifulSoup([your markup], "html5lib")

  markup_type=markup_type))
DO: [##################################################] 100%
fhserve.com: [##################################################] 100%
mh: [##################################################] 100%
Reading Munin RRD cache: (/var/lib/munin)
fhserve.com: [##################################################] 100%
DO: [##################################################] 100%
mh: [##################################################] 100%
  ✗ coercing to Unicode: need string or buffer, NoneType found

Exporting RRD databases:
  Progress: [##################################################] 100%
...
...
...
  Progress: [##############################################################################################################################################################################################################################################################################################] 573%

 ✓ Exported 19086 RRD files to XML (/tmp/munin-influxdb/xml)

InfluxDB: Please enter your connection information
  - host/handle [localhost]: 
/usr/local/lib/python2.7/dist-packages/influxdb-2.7.1-py2.7.egg/influxdb/influxdb08/client.py:551: FutureWarning: get_database_list is deprecated, and will be removed in future versions. Please use ``InfluxDBClient.get_list_database`` instead.
  - port [8086]: 
  - user [None]: root
  - password: 
  - database [munin]: 
/usr/local/lib/python2.7/dist-packages/influxdb-2.7.1-py2.7.egg/influxdb/influxdb08/client.py:194: FutureWarning: switch_db is deprecated, and will be removed in future versions. Please use ``InfluxDBClient.switch_database(database)`` instead.
Group multiple fields of the same plugin in the same time series? [y]/n: y

Uploading data to InfluxDB:
  ✓ Connection to database "munin" OK
✗ Error: 


#
```

Any ideas?

**Comment by 0xphk** [comment]
We have the same problem here on one of our boxes, where we recently migrated the rrd files from x86 architecture to x64 with `rrdtool dump & restore`

Are there any verbose logging options to see what is actual happening as just saying `Error:` isn't helpful at all. 

Thanks for any tips

**Comment by harimavoh** [comment]
hi every one! I have this problem when importing  db from munin to influxdb. can you help me please!

root@debian:/home/user/munin-influxdb# ./muninflux import
Traceback (most recent call last):
  File "bin/import.py", line 9, in <module>
    from munininfluxdb.influxdbclient import InfluxdbClient
  File "build/bdist.linux-x86_64/egg/munininfluxdb/influxdbclient.py", line 12, in <module>
ImportError: InfluxDB API is too old, please update (e.g: pip install influxdb --upgrade)
