### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by babngr** [mvonthron/munin-influxdb#3]
Hi,

I do not know much from python and perhaps the following is a stupid error but could you please help me?

After executing:
./muninflux import

Here are the messages:

```
Traceback (most recent call last):
  File "bin/import.py", line 6, in <module>
    from munininfluxdb import munin
  File "build/bdist.linux-x86_64/egg/munininfluxdb/munin.py", line 6, in <module>
  File "/usr/lib/python2.6/site-packages/munin_influxdb-0.1-py2.6.egg/munininfluxdb/settings.py", line 136
    for f, h, p, field in self.iter_fields()
      ^
SyntaxError: invalid syntax
```

Do I have something mixed up in python?

Thanks

**Comment by 0xphk** [comment]
Did you install it via `python setup.py install`?

I had a similar problem when using python3-setuptools and could'nt get it to work,
Switching to python-setuptools for 2.7 helped, maybe 2.6 isn't supported

**Comment by babngr** [comment]
Thanks @0xphk

Yes i used: `python2.6 setup.py install`

Do you believe that the following instructions will work or they will destroy the system (centos 6.5)?
http://tecadmin.net/install-python-2-7-on-centos-rhel/

Thanks again!

**Comment by 0xphk** [comment]
I'm on debian and can't say anything about red hat like systems or if this mixup could break some other things for you. I have both, python 2.7 and 3.4, installed and used setuptools for v2.7 which installed without any problems. I guess the syntax changes quite often in python :)

But after short googling it looks like your centos is rather old and comes only with 2.6 and there are many articles about getting 2.7 to work, like the one you posted or this one: http://bicofino.io/blog/2014/01/16/installing-python-2-dot-7-6-on-centos-6-dot-5/

maybe it is possible to have both python versions in parallel installed, then you could just use a virtualenv to separate your other things running on 2.6

hope this helps a little bit.
